# Playbook expects to have a Student0 folder in the directory where the playbook is run
- hosts: localhost
  gather_facts: false
  connection: local
  vars:
    # Change this to the number of copies you want
    capacity: 40
    prefix: /home
    workshop: OVWorkshop
    dir: TSS
    myrange: 1-{{capacity}}
    parse: "{{ myrange.split('-') }}"
    start: "{{parse[0]}}"
    end: "{% if parse|length > 1 %}{{parse[1]}}{% else %}{{start}}{% endif %}"

  tasks: 
    - fail:
        msg: workshop variable is empty ! Fat fingers ?!?
      when: workshop|length == 0

    - name: check variables file exists
      stat:
        path: variables_{{workshop}}.yml
      register: variables_file
    - include_vars:
        file: variables_{{workshop}}.yml
      when: variables_file.stat.exists
  
    # remove any previously created student1/ to studentn/
    - name: remove student dirs
      file: 
        path: "{{prefix}}/student{{item}}/{{dir}}/{{workshop}}"
        state: absent
      with_sequence: "{{myrange}}"

    # copy student0 n times to student1...studentn
    - name: copy master folder
      copy:
        src: "{{prefix}}/student0/{{dir}}/{{workshop}}/"
        dest: "{{prefix}}/student{{item}}/{{dir}}/{{workshop}}"
      with_sequence: "{{myrange}}"

    # find all notebooks
    - name: find jupyter notebooks
      find:
        paths: "{{prefix}}/student0/{{dir}}/{{workshop}}"
        recurse: yes
        patterns: "*.ipynb"
        excludes: '*-checkpoint.ipynb'
      register: notebooks

    # - name: display
    #   debug:
    #     msg: "{{item.0.path | regex_replace('/student0/','/student' + item.1|string + '/')}}"
    #   with_nested: 
    #     - "{{notebooks.files}}"
    #     - "{{range(1, capacity +1, 1) | list }}"
    # Replace $$I with Student ID in notebooks
    - name: student id substitution
      replace:
          path: "{{item.0.path | regex_replace('/student0/','/student' + item.1|string + '/')}}"
          regexp: \$\$I
          replace: "{{item.1}}"
      with_nested: 
        - "{{notebooks.files}}"
        - "{{range(start|int, end|int +1, 1) | list }}"

    # Replace $$variable_name with whatever is specified in variables.yml that we imported
    - name: variables substitution
      # debug:
      #   msg: 
      #     - Student{{item.2}}/{{item.0.path|basename}}
      #     - \$\${{item.1.varname}}
      #     - "{{ item.1.varsubst[item.2|string] }} "
      replace:
        path: "{{item.0.path | regex_replace('/student0/','/student' + item.2|string + '/')}}"
        regexp: \$\${{item.1.varname}}
        replace: "{{ item.1.varsubst[item.2|string] }}"
      with_nested: 
        - "{{notebooks.files}}"
        - "{{substitutions}}"
        - "{{range(start|int, end|int +1, 1) | list }}"
      when: substitutions is defined

    - name: change owner
      file:
        path: "{{prefix}}/student{{item}}/{{dir}}/{{workshop}}"
        owner: "{{item}}"
        group: jupyter
        recurse: yes
      with_sequence: "{{myrange}}"
