---
substitutions:
  - varname: OVIP
    varsubst:
      "1": 16.31.86.241
      "2": 16.31.86.241
      "3": 16.31.86.241
      "4": 16.31.86.241
      "5": 16.31.86.241
      "6": 16.31.86.241
      "7": 16.31.86.241
      "8": 16.31.86.241
      "9": 16.31.86.241
      "10": 16.31.86.241
      "11": 16.31.86.241
      "12": 16.31.86.241
      "13": 16.31.86.241
      "14": 16.31.86.241
      "15": 16.31.86.241
      "16": 16.31.86.241
      "17": 16.31.86.241
      "18": 16.31.86.241
      "19": 16.31.86.241
      "20": 16.31.86.241
      "21": 16.31.86.244
      "22": 16.31.86.244
      "23": 16.31.86.244
      "24": 16.31.86.244
      "25": 16.31.86.244
      "26": 16.31.86.244
      "27": 16.31.86.244
      "28": 16.31.86.244
      "29": 16.31.86.244
      "30": 16.31.86.244
      "31": 16.31.86.244
      "32": 16.31.86.244
      "33": 16.31.86.244
      "34": 16.31.86.244
      "35": 16.31.86.244
      "36": 16.31.86.244
      "37": 16.31.86.244
      "38": 16.31.86.244
      "39": 16.31.86.244
      "40": 16.31.86.244
  - varname: SRVNAME
    varsubst:
        "1": Synergy-Encl-1, bay 5
        "2": Synergy-Encl-2, bay 5
        "3": Synergy-Encl-3, bay 5
        "4": Synergy-Encl-1, bay 8
        "5": Synergy-Encl-2, bay 8
        "6": Synergy-Encl-3, bay 8
        "7": Synergy-Encl-1, bay 7
        "8": Synergy-Encl-2, bay 7
        "9": Synergy-Encl-3, bay 7
        "10": Synergy-Encl-1, bay 11
        "11": Synergy-Encl-2, bay 11
        "12": Synergy-Encl-3, bay 11
        "13": Synergy-Encl-1, bay 4
        "14": Synergy-Encl-2, bay 4
        "15": Synergy-Encl-3, bay 4
        "16": Synergy-Encl-1, bay 3
        "17": Synergy-Encl-2, bay 3
        "18": Synergy-Encl-3, bay 3
        "19": Synergy-Encl-1, bay 6
        "20": Synergy-Encl-2, bay 6
        "21": Synergy-Encl-1, bay 5
        "22": Synergy-Encl-2, bay 5
        "23": Synergy-Encl-3, bay 5
        "24": Synergy-Encl-1, bay 8
        "25": Synergy-Encl-2, bay 8
        "26": Synergy-Encl-3, bay 8
        "27": Synergy-Encl-1, bay 7
        "28": Synergy-Encl-2, bay 7
        "29": Synergy-Encl-3, bay 7
        "30": Synergy-Encl-1, bay 11
        "31": Synergy-Encl-2, bay 11
        "32": Synergy-Encl-3, bay 11
        "33": Synergy-Encl-1, bay 4
        "34": Synergy-Encl-2, bay 4
        "35": Synergy-Encl-3, bay 4
        "36": Synergy-Encl-1, bay 3
        "37": Synergy-Encl-2, bay 3
        "38": Synergy-Encl-3, bay 3
        "39": Synergy-Encl-1, bay 6
        "40": Synergy-Encl-2, bay 6
  - varname: SHT
    varsubst:
        "1": SY 480 Gen9 1
        "2": SY 480 Gen9 1
        "3": SY 480 Gen9 1
        "4": SY 480 Gen9 3
        "5": SY 480 Gen9 3
        "6": SY 480 Gen9 3
        "7": SY 480 Gen9 2
        "8": SY 480 Gen9 2
        "9": SY 480 Gen9 2
        "10": SY 480 Gen10 1
        "11": SY 480 Gen10 1
        "12": SY 480 Gen10 1
        "13": SY 660 Gen9 2
        "14": SY 660 Gen9 2
        "15": SY 660 Gen9 2
        "16": SY 660 Gen9 1
        "17": SY 660 Gen9 1
        "18": SY 660 Gen9 1
        "19": SY 660 Gen10 1
        "20": SY 660 Gen10 1
        "21": SY 480 Gen9 2
        "22": SY 480 Gen9 2
        "23": SY 480 Gen9 2
        "24": SY 480 Gen9 3
        "25": SY 480 Gen9 3
        "26": SY 480 Gen9 3
        "27": SY 480 Gen9 1
        "28": SY 480 Gen9 1
        "29": SY 480 Gen9 1
        "30": SY 480 Gen10 1
        "31": SY 480 Gen10 1
        "32": SY 480 Gen10 1
        "33": SY 660 Gen9 1
        "34": SY 660 Gen9 1
        "35": SY 660 Gen9 1
        "36": SY 660 Gen9 2
        "37": SY 660 Gen9 2
        "38": SY 660 Gen9 2
        "39": SY 660 Gen10 1
        "40": SY 660 Gen10 1
  - varname: SPTNAME
    varsubst:
      "1": Template for 480 Gen9 1
      "2": Template for 480 Gen9 1
      "3": Template for 480 Gen9 1
      "4": Template for 480 Gen9 3
      "5": Template for 480 Gen9 3
      "6": Template for 480 Gen9 3
      "7": Template for 480 Gen9 2
      "8": Template for 480 Gen9 2
      "9": Template for 480 Gen9 2
      "10": Template for 480 Gen10 1
      "11": Template for 480 Gen10 1
      "12": Template for 480 Gen10 1
      "13": Template for 660 Gen9 2
      "14": Template for 660 Gen9 2
      "15": Template for 660 Gen9 2
      "16": Template for 660 Gen9 1
      "17": Template for 660 Gen9 1
      "18": Template for 660 Gen9 1
      "19": Template for 660 Gen10 1
      "20": Template for 660 Gen10 1
      "21": Template for 480 Gen9 2
      "22": Template for 480 Gen9 2
      "23": Template for 480 Gen9 2
      "24": Template for 480 Gen9 3
      "25": Template for 480 Gen9 3
      "26": Template for 480 Gen9 3
      "27": Template for 480 Gen9 1
      "28": Template for 480 Gen9 1
      "29": Template for 480 Gen9 1
      "30": Template for 480 Gen10 1
      "31": Template for 480 Gen10 1
      "32": Template for 480 Gen10 1
      "33": Template for 660 Gen9 1
      "34": Template for 660 Gen9 1
      "35": Template for 660 Gen9 1
      "36": Template for 660 Gen9 2
      "37": Template for 660 Gen9 2
      "38": Template for 660 Gen9 2
      "39": Template for 660 Gen10 1
      "40": Template for 660 Gen10 1
